/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SanPhamCuaEmRouteImport } from './routes/san-pham-cua-em'
import { Route as HocTiengVietRouteImport } from './routes/hoc-tieng-viet'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const SanPhamCuaEmRoute = SanPhamCuaEmRouteImport.update({
  id: '/san-pham-cua-em',
  path: '/san-pham-cua-em',
  getParentRoute: () => rootRouteImport,
} as any)
const HocTiengVietRoute = HocTiengVietRouteImport.update({
  id: '/hoc-tieng-viet',
  path: '/hoc-tieng-viet',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/hoc-tieng-viet': typeof HocTiengVietRoute
  '/san-pham-cua-em': typeof SanPhamCuaEmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/hoc-tieng-viet': typeof HocTiengVietRoute
  '/san-pham-cua-em': typeof SanPhamCuaEmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/hoc-tieng-viet': typeof HocTiengVietRoute
  '/san-pham-cua-em': typeof SanPhamCuaEmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/hoc-tieng-viet' | '/san-pham-cua-em'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/hoc-tieng-viet' | '/san-pham-cua-em'
  id: '__root__' | '/' | '/dashboard' | '/hoc-tieng-viet' | '/san-pham-cua-em'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HocTiengVietRoute: typeof HocTiengVietRoute
  SanPhamCuaEmRoute: typeof SanPhamCuaEmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/san-pham-cua-em': {
      id: '/san-pham-cua-em'
      path: '/san-pham-cua-em'
      fullPath: '/san-pham-cua-em'
      preLoaderRoute: typeof SanPhamCuaEmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoc-tieng-viet': {
      id: '/hoc-tieng-viet'
      path: '/hoc-tieng-viet'
      fullPath: '/hoc-tieng-viet'
      preLoaderRoute: typeof HocTiengVietRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HocTiengVietRoute: HocTiengVietRoute,
  SanPhamCuaEmRoute: SanPhamCuaEmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
